---
# handlers file for nagios
- name: restart apache
  service:
    name: httpd
    enabled: yes
    state: reloaded
- name: restart nagios
  service:
    name: nagios
    enabled: yes
    state: reloaded